default:
  http_metas:
    content-type: text/html

  metas:
    title:        test
    description:  mamba
    keywords:     repeticija, solate
    language:     si
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     on
  layout:         layout
