propel:
  clanek:
    id:           ~
    title:        { type: varchar(255), required: true }
    excerpt:      { type: longvarchar }
    body:         { type: longvarchar }
    created_at:   ~
    updated_at:   ~
    user_id:   ~

  komentar:
    id:           ~
    clanek_id : ~
    author:       { type: varchar(255) }
    email:        { type: varchar(255) }
    body:         { type: longvarchar }
    created_at:   ~

  user:
    id:           ~
#   sf_user:      { type: integer, primaryKey: true, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade}
    nickname:     { type: varchar(255) }
    name:         { type: varchar(255) }
    email:         { type: varchar(255) }
    password: { type: varchar(255) }