propel:
  blog_post:
    id:           ~
    title:        { type: varchar(255), required: true }
    excerpt:      { type: longvarchar }
    body:         { type: longvarchar }
    created_at:   ~

  blog_comment:
    id:           ~
    blog_post_id: ~
    author:       { type: varchar(255) }
    email:        { type: varchar(255) }
    body:         { type: longvarchar }
    created_at:   ~

  vprasanje:
    id:           ~
    naslov:       { type: varchar(255) }
    text:         { type: varchar(255) }
    nickname:     { type: varchar(255) }
    created_at:   ~

  odgovor:
    id:           ~
    vprasanje_id:  { type: integer, foreignTable: vprasanje, foreignReference: id}
    svetovalec_id: { type: integer, foreignTable: svetovalec, foreignReference: id}
    naslov:       { type: varchar(255) }
    text:         { type: varchar(255) }

  category:
    id:           ~
    naslov:       { type: varchar(255) }
    text:         { type: varchar(255) }

  svetovalec:
    id:           ~
#    sf_user:      { type: integer, primaryKey: true, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade}
    nickname:     { type: varchar(255) }
    name:         { type: varchar(255) }

  vprasanje_category:
    vprasanje:         { type: integer, primaryKey: true, required: true, foreignTable: vprasanje, foreignReference: id}
    category:          { type: integer, primaryKey: true, required: true, foreignTable: category, foreignReference: id}      
  svetovalec_category:
    svetovalec:         { type: integer, primaryKey: true, required: true, foreignTable: svetovalec, foreignReference: id}
    category:          { type: integer, primaryKey: true, required: true, foreignTable: category, foreignReference: id}   

  tags:
    name:         { type: varchar(255), required: true, primaryKey: true}
    vprasanje_id: { type: integer, primaryKey: true,  required: true, foreignTable: vprasanje, foreignReference: id}
  
  notifications:
    id: ~
    odgovor_id: ~
    email: { type: varchar(255), required: false, primaryKey: true}